# Makefile for R-Mobile framebuffer device driver
#
obj-$(CONFIG_FB_R_MOBILE_NT35510)      += panel_nt35510.o
obj-$(CONFIG_FB_R_MOBILE_NT35516)      += panel_nt35516.o
obj-$(CONFIG_FB_R_MOBILE_NT35590)      += panel_nt35590.o
obj-$(CONFIG_FB_R_MOBILE_VX5B3D)       += panel_vx5b3d.o
obj-$(CONFIG_FB_R_MOBILE_HX8389B)       += panel_hx8389b.o
obj-$(CONFIG_FB_R_MOBILE_HX8369B)       += panel_hx8369b.o
obj-$(CONFIG_FB_R_MOBILE_S6E88A0)      += dynamic_aid.o panel_s6e88a0.o
obj-$(CONFIG_FB_R_MOBILE_HX8389B_TRULY)       += panel_hx8389b_truly.o
obj-$(CONFIG_LDI_MDNIE)        += mdnie.o mdnie_tuning.o
